### ISSUE TITLE
Update for sensor.jumbo_orders fails 

### ISSUE THREAD

**Issue by TheRedBull205** [peternijssen/home-assistant-jumbo#7]
Just added this plugin to HA, after the restart i added the credentials to the config and did another restart. But i currently only have 2 sensors and are missing the basket:
![Knipsel](https://user-images.githubusercontent.com/17354992/80868772-e734b780-8c9c-11ea-8b95-f60f5fb9a581.PNG)
Also tried to add something to my basket on jumbo.com but that didn't help.

```
2020-05-02 10:45:57 DEBUG (MainThread) [jumbo_api.jumbo_api] Requesting update from https://mobileapi.jumbo.com/v9/stores/slots?storeId=3659&fulfilment=homeDelivery
2020-05-02 10:46:00 ERROR (MainThread) [jumbo_api.jumbo_api] Unable to perform request b'{"code":"4019","message":"No Slots For Date Requested"}'
2020-05-02 10:46:00 ERROR (MainThread) [homeassistant.components.sensor] jumbo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/jumbo/sensor.py", line 101, in async_update
    await self._data.async_update()
  File "/config/custom_components/jumbo/sensor.py", line 80, in async_update
    self.basket = self._api.get_basket()
  File "/usr/local/lib/python3.7/site-packages/jumbo_api/jumbo_api.py", line 136, in get_basket
    self._update()
  File "/usr/local/lib/python3.7/site-packages/jumbo_api/jumbo_api.py", line 55, in _update
    self._update_time_slots()
  File "/usr/local/lib/python3.7/site-packages/jumbo_api/jumbo_api.py", line 106, in _update_time_slots
    if response['timeSlots'] is False:
TypeError: 'bool' object is not subscriptable
```

**Comment by peternijssen** [comment]
Thanks for your report. I think it crashes because no timeslots were available. I didn't had that case yet but now I know what it responds. Will fix it tomorrow.
